### ISSUE TITLE
History not preserved from old repo

### ISSUE THREAD

**Issue by pR0Ps** [feediron/feediron-recipes#2]
The history of the recipes wasn't preserved when moving to this new repo. Since a lot of the recipes are large regular expressions, any context in the commit history is valuable for future contributors trying to fix something.

Ex: I made the following commit in the old repo: https://github.com/feediron/ttrss_plugin-feediron/commit/04c74bfa75d171abe893eb9f308aa2dea2899f1f . Not all commit messages are that detailed, but I think there's still value to them.

My current fork of this repo has all the history preserved: https://github.com/pR0Ps/feediron-recipes. Would you consider replacing this repo with the content of that one?

Like so:
```bash
cd <your recipes repo>
git remote add pR0Ps https://github.com/pR0Ps/feediron-recipes.git
git fetch pR0Ps
git checkout master
git reset --hard pR0Ps/master
git push --force origin master
```

Alternatively, you can do the same thing I did from a fresh copy of your repo using the bash script below. This way you don't have to trust that I haven't manipulated the code in some way.

It will clone a fresh copy of the repo and rewrite the history to preserve the recipes folder and nothing else. It then cherry-picks your commits that added the readme, license, and github templates. There's probably a more optimal way of doing this but meh.

The last commented out line force-pushes the new tree up to the master branch of this repo.

```bash
# Grab a fresh copy of the repo
git clone https://github.com/feediron/ttrss_plugin-feediron.git
cd ttrss_plugin-feediron

# Check out the last commit with recipes in it
git checkout e22c0dfbdd30cdb8247657e2de19b59ccae2bcf4~1

# Split the history of the recipes folder into its own branch
git subtree split --prefix=recipes/ -b recipes
git checkout recipes

# Rewrite history to move all the recipes to a folder called "recipes"
git filter-branch --tree-filter "mkdir recipes; git mv -k * recipes" HEAD

# Add the refs from the current recipes repo
# git remote add https://github.com/feediron/feediron-recipes.git # HTTPS
git remote add recipes git@github.com:feediron/feediron-recipes.git
git fetch recipes

# Cherry pick commits that add `LICENCE`, `README.md`, and `.github/*_TEMPLATE.md`
git cherry-pick 150c0a3b58d5df29e3412b550af4e3ebd4963e6e 3910db566e14ba666a0b5d847bb0c2bce153de40 9911bdffda833003f18c5b589aaeee319d3f1518

# Explore the history and file tree to make sure everything worked properly.
# When you're satisfied, use the following command to push the current HEAD up
# to the master branch of this repo:
#     git push --force recipes HEAD:master
```
-----------------

Note that I changed the folder of the recipes from "general" to "recipes".

I'm assuming "general" is the beginning of a categorization effort? I was going to make another issue about this, but figured I would lump it in here: I don't think categorization is the way to go for this. Not everyone's categories are the same and loads of sites would be considered to be in multiple categories. Personally, I think it would actually make finding a recipe harder, not easier. Right now you can select the dropdown, type the first letter and get pretty close to the site you want. With categories this probably won't be the case. Also, unless they're localized, the experience will get strictly worse from a non-English perspective.

IMO a much better way of solving the problem of too many options in the dropdown would be to limit them to the ones you actually want, something like https://github.com/feediron/ttrss_plugin-feediron/issues/19 .

Either way, your repo, your rules. It's pretty easy to change the script if you want the folder named "general".

**Comment by dugite-code** [comment]
Excellent points, the commit history is something I overlooked. I'll definitely follow your advice on this.

> I'm assuming "general" is the beginning of a categorization effort?

A bit, multiple locations will show in the main list already. Given I want to re-name filters based on their domain name having both feediron/ttrss_plugin-feediron#19 would be good to have a way of defining different use-cases i.e. summaries, pictures ect and finding the domain you want. I'll keep the general folder as that would be a breaking change for current installs anyway.

Also what I want to do is allow the linking of custom repositories as I keep a bunch of private filters in a private repository.
